# Generated by Django 5.1.4 on 2024-12-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Morning', 'Morning (7 AM - 3 PM)'), ('Afternoon', 'Afternoon (3 PM - 11 PM)'), ('Night', 'Night (11 PM - 7 AM)')], max_length=10, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_students', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('school', models.CharField(max_length=100)),
                ('lchaim_training_completed', models.BooleanField(default=False)),
                ('police_check', models.BooleanField(default=False)),
                ('med_docs', models.BooleanField(default=False)),
                ('hours_requested', models.IntegerField(null=True)),
                ('hours_completed', models.PositiveIntegerField(default=0)),
                ('shift_requested', models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekends', 'Weekends')], max_length=10)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('lchaim_orientation_date', models.DateField(null=True)),
                ('skills_book_completed', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Training', 'Training'), ('Graduated', 'Graduated')], default='Training', max_length=10)),
                ('assigned_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.shift')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.college')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='students.studentprofile')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.shift')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_logs', to='students.studentprofile')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
