# Generated by Django 4.2.17 on 2024-12-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(choices=[('School of Engineering', 'School of Engineering'), ('School of Arts', 'School of Arts'), ('School of Science', 'School of Science')], max_length=50),
        ),
    ]
