# Generated by Django 5.1.4 on 2024-12-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_hours_completed_volunteerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerlog',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
    ]
