# Generated by Django 5.1.4 on 2024-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_volunteerlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerlog',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerlog',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
