# Generated by Django 5.1.4 on 2024-12-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_volunteerlog_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerlog',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
