# Generated by Django 5.1.4 on 2024-12-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_volunteerlog_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='hours_requested',
            field=models.IntegerField(null=True),
        ),
    ]
