# Generated by Django 5.1.4 on 2024-12-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_studentprofile_hours_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('Training', 'Training'), ('Graduated', 'Graduated')], default='Training', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='lchaim_orientation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
