# Generated by Django 5.1.4 on 2024-12-28 15:24

from django.db import migrations

def create_default_shifts(apps, schema_editor):
    Shift = apps.get_model('students', 'Shift')
    if not Shift.objects.filter(type='Morning').exists():
        Shift.objects.create(
            type='Morning',
            start_time='07:00',
            end_time='15:00',
            max_students=5
        )
    if not Shift.objects.filter(type='Afternoon').exists():
        Shift.objects.create(
            type='Afternoon',
            start_time='15:00',
            end_time='23:00',
            max_students=5
        )
    if not Shift.objects.filter(type='Night').exists():
        Shift.objects.create(
            type='Night',
            start_time='23:00',
            end_time='07:00',
            max_students=5
        )

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_shifts),
    ]
